language: node_js
node_js:
  - "6.1"
  - "4.4"
  - "0.12"
  - "0.10"

script: "npm test"
after_script: "npm install if-node-version && npm install coveralls && if-node-version '>=4' cat ./coverage/lcov.info | coveralls"
